
image:
  file: gitpod/Dockerfile
tasks:
- name: Start Couchbase with Fluent Bit
  before: /fluent-entrypoint.sh
- name: Create Bucket
  init: while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' -u Administrator:password localhost:8091/pools/default)" != "200" ]]; do sleep 5; done && couchbase-cli bucket-create -c localhost:8091 --username Administrator --password password --bucket default --bucket-type couchbase --bucket-ramsize 256
ports:
  - port: 8091
    onOpen: open-preview
  - port: 8092-10000
    onOpen: ignore
  - port: 4369
    onOpen: ignore
  - port: 2020
    onOpen: ignore