apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cbes.fullname" . }}
  labels:
    {{- include "cbes.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "cbes.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        rollme: {{ .Values.replicaCount | quote }}
        {{- include "cbes.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
